### ISSUE TITLE
Use fsthet with sliding-windows calculated Fst values

### ISSUE THREAD

**Issue by Yung-Chien** [spflanagan/fsthet_analysis#1]
Hi @spflanagan ,
I'd like to find outlier of my Fst calculated by sliding-windows , and an issue appears that a window include many genotypes of many snps, it's hardly to difine a value like 0101 or 0102 to generate an input file for function _my.read.genepop_. So how could I create this input file?
Thanks in advances,
Yung

**Comment by spflanagan** [comment]
Hi Yung-Chien,
Several tools are available for converting data formats. A commonly-used one is PGDSpider (http://www.cmpg.unibe.ch/software/PGDSpider/), which will allow you to convert your data into genepop format.

Does that answer your question?
All the best,
Sarah
