### ISSUE TITLE
find.outliers function

### ISSUE THREAD

**Issue by BelenJM** [spflanagan/fsthet_analysis#2]
Hi,
I am somehow getting an error when running the find.outliers function

> outliers <- find.outliers(fsts,boot.out=quant.list)
Error in names(x) <- value : 
  'names' attribute [4] must be the same length as the vector [1]

So I went around it and selected outliers directly from the plot of He vs. Fst, and the quantiles, using identify function from R{graphics}. So for example, I picked up all the SNPs over the upper quantile (SNPs with the ID on the plot).  
![image](https://user-images.githubusercontent.com/13405546/92383702-1d80b880-f10f-11ea-832d-0738233bbf6f.png)
I wanted to hear from you that this is basically what the find.outliers function would do. Given that the method discards the most extreme Fst value-SNPs from each quantile, I am doubting now that maybe those discarded SNPs are also among those I highlighted over the upper quantile line.
Thanks a lot!

**Comment by spflanagan** [comment]
The find.outliers function does simply identify outliers beyond the bounds of the confidence intervals for each Ht bin. If you can provide a reproducible example (all of the code to reproduce the error and your dataset or a subset of your dataset) I can try to identify why you're getting and error.

**Comment by BelenJM** [comment]
Hej Sarah, thanks a lot for the offer. I emailed you the dataset/R code. Looking forward to your feedback.

**Comment by spflanagan** [comment]
It seems that the main issue you ran into was not using the `fst.boot` output in the `find.outliers` function -- this is important because the output from `fst.boot()` is in a specific format that `find.outliers()` is looking for. Using the data you shared, the following code worked for me without any errors.

```
devtools::install_github("spflanagan/fsthet_analysis/fsthet")
require(fsthet)
gpop <- my.read.genepop("data.genepop.txt")
fsts <- calc.actual.fst(gpop)
quant.out<-fst.boot(gpop,bootstrap = FALSE)
outliers<-find.outliers(fsts,boot.out=quant.out)
```
